### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by Yberion** [paddls/ngx-common#33]
Salut @oscar-guerin @thomasnisole,

Vous semble-t-il possible d'avoir une version compatible avec Angular 16 ?

Je vois que la version "autorisée" c'est `>= 15.0.0`, mais il est conseillé par Angular d'avoir une nouvelle version de package à chaque version majeur d'Angular.

PR accepté ?

Bonne journée.

**Comment by thomasnisole** [comment]
Salut @Yberion,

Aucun problème si tu veux faire la PR, sinon il faudra attendre quelques jours pour que nous prenions le temps de le faire pour toutes nos librairies.

Merci et bonne journée à toi.

**Comment by Yberion** [comment]
Parfait, je fais ça dans le week-end si je trouve du temps !
